# Site settings
title: Rylan Graham
header-img: img/home-bg.jpg
email: rylan.graham@ucalgary.ca
description: "An urban planner's blog."
baseurl: ""
url: "http://rylangraham.github.io"
twitter_username: rylangraham
github_username:  RylanGraham

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

prose:
  # rooturl: 'source/_posts'
  siteurl: 'http://rylangraham.github.io'
  media: 'img'
